name: leon-utilities module Release
on:
  push:
    tags:
      - 'v*'

jobs:
  workflow-lint:
    uses: ./.github/workflows/runner-module-lint.yaml

#  workflow-test-android:
#    needs: [ workflow-lint ]
#    uses: ./.github/workflows/runner-module-test-android.yaml
#    secrets:
#      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

#  workflow-test-unit:
#    needs: [ workflow-lint ]
#    uses: ./.github/workflows/runner-module-test-unit.yaml
#    secrets:
#      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

#      - name: Publish to GitHub Package Registry 🚀
#        run: bash ./gradlew :leon-utilities:publish
#        env:
#          GPR_USER: ${{ github.actor }}
#          GPR_KEY: ${{ secrets.GITHUB_TOKEN }}

  workflow-publish:
    needs: [ workflow-lint ]
    uses: ./.github/workflows/runner-module-publish-aar.yaml