name: Run Android Lint

on:
  workflow_call:
    inputs:
      MODULE_NAME:
        description: 'Which module you need to run this flow on...'
        type: string
        required: true

jobs:
  lint:
    name: Run Android Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Run Lint
        run: ./gradlew ${{ inputs.MODULE_NAME }}:lint

      - name: Upload html test report
        # Upload report to ubuntu server to be used on another action...
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: lint_report
          path: ${{ inputs.MODULE_NAME }}/build/reports/lint-results-*
