name: Generate Github Release And Upload Android AAR 🗳

on:
  workflow_call:
    inputs:
      UPLOADED_FILES_ID:
        description: 'The id for the files needs to be downloaded from artifacts and uploaded to git release..'
        type: string
        required: true
    # Map the workflow outputs to job outputs
    outputs:
      release_url:
        description: Release url link
        value: ${{ jobs.upload_matrix_artifacts.outputs.url }}

jobs:
  git_release:
    name: Generate Github Release
    runs-on: ubuntu-latest
    # Map the job outputs to step outputs
    outputs:
      release_url: ${{ steps.create_release.outputs.upload_url }}

    steps:
      - name: Create Release ✅
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false

  upload_matrix_artifacts:
    needs: [ git_release ]
    name: Upload Generated Artifacts to Git Release.
    runs-on: ubuntu-latest
    # Map the job outputs to step outputs
    outputs:
      url: ${{ steps.upload-release-asset.outputs.browser_download_url }}

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: ${{ inputs.UPLOADED_FILES_ID }}
          path: ${{ github.workspace }}/${{ inputs.UPLOADED_FILES_ID }}

      - name: List downloaded files
        run: ls ${{ github.workspace }}/${{ inputs.UPLOADED_FILES_ID }}

      - name: Upload Generated Android AAR 🗳
        id: upload-release-asset
        uses: sekwah41/upload-release-assets@v1.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.git_release.outputs.release_url }}
          asset_path: ${{ github.workspace }}/${{ inputs.UPLOADED_FILES_ID }}/**-release.aar
          asset_content_type: application/aar
