name: Run Unit-test

on:
  workflow_call:
    inputs:
      MODULE_NAME:
        description: 'Which module you need to run this flow on...'
        type: string
        required: true

jobs:
  unit-test:
    name: Run Unit test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Run tests
        run: ./gradlew ${{ inputs.MODULE_NAME }}:testDebugUnitTest

      - name: Upload unit test report
        # Upload report to ubuntu server to be used on another action...
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: unit_test_report
          path: ${{ inputs.MODULE_NAME }}/build/reports/tests/testDebugUnitTest/
